package pptx

import (
	"archive/zip"
	"bytes"
	"fmt"
	"io"
	"sort"
	"strings"
)

// writeWithTemplate serializes the presentation using the design parts from the
// configured template. It regenerates the presentation part, content types and
// relationships, copies the template's theme/master/layout parts verbatim, and
// emits new slides that reference the template's layouts.
func (p *Presentation) writeWithTemplate(w io.Writer) (int64, error) {
	t := p.Template

	width, height := p.Width, p.Height
	if width == 0 {
		width = t.width
	}
	if height == 0 {
		height = t.height
	}
	if width == 0 {
		width = DefaultSlideWidth
	}
	if height == 0 {
		height = DefaultSlideHeight
	}

	n := len(p.Slides)

	var notesSlideNums []int
	for i, s := range p.Slides {
		if s.Note != "" {
			notesSlideNums = append(notesSlideNums, i+1)
		}
	}
	hasNotes := len(notesSlideNums) > 0

	textParts := map[string]string{}
	binParts := map[string][]byte{}

	// Copy template design parts verbatim.
	for name, data := range t.designParts {
		binParts[name] = data
	}

	// Core/app + props generated by slidown. The template-tracking hash (used by
	// the incremental rebuild to detect a template switch) is embedded in
	// presentation.xml's extLst rather than a loose part, so every part in the
	// package has a declared content type and PowerPoint does not flag it.
	textParts["_rels/.rels"] = rootRels
	textParts["docProps/core.xml"] = coreProps(p.Title)
	textParts["docProps/app.xml"] = appProps
	textParts["ppt/presentation.xml"] = t.presentationXML(width, height, n, hasNotes, t.TemplateHash())
	textParts["ppt/_rels/presentation.xml.rels"] = t.presentationRelsXML(n, hasNotes)

	// presProps/viewProps: use template's if present, else generate.
	if t.presPropsPart == "" {
		textParts["ppt/presProps.xml"] = presProps
	}
	if t.viewPropsPart == "" {
		textParts["ppt/viewProps.xml"] = viewProps
	}

	// The notes master slides reference. Prefer the template's own notes master
	// (carried in designParts) so notes inherit its design and its theme stays
	// referenced; otherwise emit slidown's built-in one when the deck has notes.
	notesMasterName := t.notesMasterPart
	if notesMasterName == "" {
		notesMasterName = "ppt/notesMasters/notesMaster1.xml"
		if hasNotes {
			textParts["ppt/notesMasters/notesMaster1.xml"] = notesMaster1()
			textParts["ppt/notesMasters/_rels/notesMaster1.xml.rels"] = t.notesMasterRelsXML()
		}
	}
	notesMasterTarget := "../" + strings.TrimPrefix(notesMasterName, "ppt/")

	mediaIdx := 0
	mediaCount := t.maxMediaIndex()
	mediaIdx = mediaCount // continue numbering after template media to avoid clashes
	for i, s := range p.Slides {
		xml, rels, media := renderSlide(s, &mediaIdx)
		textParts[fmt.Sprintf("ppt/slides/slide%d.xml", i+1)] = xml

		layout := t.LayoutByName(s.LayoutName)
		if layout == nil {
			layout = t.ContentLayout()
		}
		layoutTarget := "../slideLayouts/" + baseName(layout.PartName)
		all := []slideRel{{
			id:     "rId1",
			relTyp: "http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout",
			target: layoutTarget,
		}}
		all = append(all, rels...)
		if s.Note != "" {
			all = append(all, slideRel{
				id:     "rId500",
				relTyp: "http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesSlide",
				target: fmt.Sprintf("../notesSlides/notesSlide%d.xml", i+1),
			})
			textParts[fmt.Sprintf("ppt/notesSlides/notesSlide%d.xml", i+1)] = notesSlideXML(s.Note)
			textParts[fmt.Sprintf("ppt/notesSlides/_rels/notesSlide%d.xml.rels", i+1)] = notesSlideRels(i+1, notesMasterTarget)
		}
		textParts[fmt.Sprintf("ppt/slides/_rels/slide%d.xml.rels", i+1)] = slideRelsXML(all)
		for _, m := range media {
			binParts["ppt/media/"+m.name] = m.data
		}
	}

	textParts["[Content_Types].xml"] = t.contentTypesXML(n, notesSlideNums)

	return zipWrite(w, textParts, binParts)
}

// presentationMetaURI identifies slidown's presentation-level metadata
// extension embedded in presentation.xml's extLst. It carries the template hash
// (previously stored as a loose ppt/slidownMeta part) so the value lives inside
// a declared, referenced part instead of an undeclared one that PowerPoint
// strips on repair.
const presentationMetaURI = "{2B9E6F14-7C3D-4A85-9E21-5F0B8D3C6A47}"

// presentationMetaExt renders the presentation-level extLst carrying the
// template hash, or an empty string when hash is empty.
func presentationMetaExt(hash string) string {
	if hash == "" {
		return ""
	}
	return `<p:extLst><p:ext uri="` + presentationMetaURI + `">` +
		`<slidown:meta xmlns:slidown="` + fingerprintNS + `" v="` + escapeXML(hash) + `"/>` +
		`</p:ext></p:extLst>`
}

// presentationXML generates ppt/presentation.xml referencing the template's
// masters and the new slides. templateHash is embedded in the presentation
// extLst for incremental-rebuild template-change detection.
func (t *Template) presentationXML(width, height int64, slideCount int, hasNotes bool, templateHash string) string {
	var b strings.Builder
	b.WriteString(xmlDecl)
	b.WriteString(`<p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" ` +
		`xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" ` +
		`xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" saveSubsetFonts="1">`)
	b.WriteString(`<p:sldMasterIdLst>`)
	for i := range t.masterParts {
		b.WriteString(fmt.Sprintf(`<p:sldMasterId id="%d" r:id="rId%d"/>`, 2147483648+int64(i), i+1))
	}
	b.WriteString(`</p:sldMasterIdLst>`)
	if t.notesMasterPart != "" || hasNotes {
		b.WriteString(`<p:notesMasterIdLst><p:notesMasterId r:id="rId902"/></p:notesMasterIdLst>`)
	}
	if t.handoutMasterPart != "" {
		b.WriteString(`<p:handoutMasterIdLst><p:handoutMasterId r:id="rId903"/></p:handoutMasterIdLst>`)
	}
	b.WriteString(`<p:sldIdLst>`)
	slideRelStart := len(t.masterParts) + 1 + 1 // masters + theme
	for i := 0; i < slideCount; i++ {
		b.WriteString(fmt.Sprintf(`<p:sldId id="%d" r:id="rId%d"/>`, 256+i, slideRelStart+i))
	}
	b.WriteString(`</p:sldIdLst>`)
	b.WriteString(fmt.Sprintf(`<p:sldSz cx="%d" cy="%d"/><p:notesSz cx="6858000" cy="9144000"/>`, width, height))
	b.WriteString(presentationMetaExt(templateHash))
	b.WriteString(`</p:presentation>`)
	return b.String()
}

func (t *Template) presentationRelsXML(slideCount int, hasNotes bool) string {
	var b strings.Builder
	b.WriteString(xmlDecl)
	b.WriteString(`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">`)
	rid := 1
	for _, m := range t.masterParts {
		b.WriteString(fmt.Sprintf(`<Relationship Id="rId%d" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="%s"/>`,
			rid, strings.TrimPrefix(m, "ppt/")))
		rid++
	}
	// theme relationship (rId after masters)
	themeTarget := strings.TrimPrefix(t.themePart, "ppt/")
	b.WriteString(fmt.Sprintf(`<Relationship Id="rId%d" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="%s"/>`, rid, themeTarget))
	rid++
	for i := 0; i < slideCount; i++ {
		b.WriteString(fmt.Sprintf(`<Relationship Id="rId%d" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide%d.xml"/>`,
			rid, i+1))
		rid++
	}
	presProps := "presProps.xml"
	if t.presPropsPart != "" {
		presProps = strings.TrimPrefix(t.presPropsPart, "ppt/")
	}
	viewProps := "viewProps.xml"
	if t.viewPropsPart != "" {
		viewProps = strings.TrimPrefix(t.viewPropsPart, "ppt/")
	}
	b.WriteString(fmt.Sprintf(`<Relationship Id="rId900" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/presProps" Target="%s"/>`, presProps))
	b.WriteString(fmt.Sprintf(`<Relationship Id="rId901" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/viewProps" Target="%s"/>`, viewProps))
	// Notes master: prefer the template's own (so its theme stays referenced and
	// notes inherit its design); fall back to slidown's built-in one when the
	// deck has notes but the template supplies none.
	if t.notesMasterPart != "" || hasNotes {
		notesTarget := "notesMasters/notesMaster1.xml"
		if t.notesMasterPart != "" {
			notesTarget = strings.TrimPrefix(t.notesMasterPart, "ppt/")
		}
		b.WriteString(fmt.Sprintf(`<Relationship Id="rId902" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesMaster" Target="%s"/>`, notesTarget))
	}
	if t.handoutMasterPart != "" {
		b.WriteString(fmt.Sprintf(`<Relationship Id="rId903" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/handoutMaster" Target="%s"/>`, strings.TrimPrefix(t.handoutMasterPart, "ppt/")))
	}
	b.WriteString(`</Relationships>`)
	return b.String()
}

func (t *Template) notesMasterRelsXML() string {
	themeTarget := "../" + strings.TrimPrefix(t.themePart, "ppt/")
	return xmlDecl +
		`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
		fmt.Sprintf(`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="%s"/>`, themeTarget) +
		`</Relationships>`
}

func (t *Template) contentTypesXML(slideCount int, notesSlideNums []int) string {
	var b strings.Builder
	b.WriteString(xmlDecl)
	b.WriteString(`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">`)
	// Slidown's baseline Default extensions. The template may add more (emf,
	// svg, wdp, ...); those are emitted below and deduped against this set.
	baseDefaults := []struct{ ext, ct string }{
		{"rels", "application/vnd.openxmlformats-package.relationships+xml"},
		{"xml", "application/xml"},
		{"png", "image/png"},
		{"jpeg", "image/jpeg"},
		{"jpg", "image/jpeg"},
		{"gif", "image/gif"},
	}
	seenExt := make(map[string]bool, len(baseDefaults))
	for _, d := range baseDefaults {
		b.WriteString(fmt.Sprintf(`<Default Extension="%s" ContentType="%s"/>`, d.ext, d.ct))
		seenExt[d.ext] = true
	}
	// Preserve any extra Default declarations from the template (e.g. emf, svg,
	// wdp). Without these PowerPoint reports "unknown content type" and offers
	// to repair the package.
	extraExts := make([]string, 0, len(t.defaultTypes))
	for ext := range t.defaultTypes {
		if seenExt[ext] {
			continue
		}
		extraExts = append(extraExts, ext)
	}
	sort.Strings(extraExts)
	for _, ext := range extraExts {
		b.WriteString(fmt.Sprintf(`<Default Extension="%s" ContentType="%s"/>`, ext, t.defaultTypes[ext]))
	}
	b.WriteString(`<Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>`)
	b.WriteString(`<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>`)
	b.WriteString(`<Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>`)
	if t.presPropsPart == "" {
		b.WriteString(`<Override PartName="/ppt/presProps.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presProps+xml"/>`)
	}
	if t.viewPropsPart == "" {
		b.WriteString(`<Override PartName="/ppt/viewProps.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.viewProps+xml"/>`)
	}
	// Design part overrides (themes, masters, layouts, presProps/viewProps,
	// tableStyles) in a stable order.
	names := make([]string, 0, len(t.partTypes))
	for name := range t.partTypes {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		b.WriteString(fmt.Sprintf(`<Override PartName="/%s" ContentType="%s"/>`, name, t.partTypes[name]))
	}
	for i := 1; i <= slideCount; i++ {
		b.WriteString(fmt.Sprintf(`<Override PartName="/ppt/slides/slide%d.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`, i))
	}
	if len(notesSlideNums) > 0 {
		// The template's own notes master (if any) is already declared via the
		// partTypes loop above; only declare the built-in one here to avoid a
		// duplicate Override.
		if t.notesMasterPart == "" {
			b.WriteString(`<Override PartName="/ppt/notesMasters/notesMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.notesMaster+xml"/>`)
		}
		for _, num := range notesSlideNums {
			b.WriteString(fmt.Sprintf(`<Override PartName="/ppt/notesSlides/notesSlide%d.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.notesSlide+xml"/>`, num))
		}
	}
	b.WriteString(`</Types>`)
	return b.String()
}

// maxMediaIndex returns the highest imageN index already present in the
// template's media, so generated media can continue numbering without clashes.
func (t *Template) maxMediaIndex() int {
	max := 0
	for name := range t.designParts {
		if !strings.HasPrefix(name, "ppt/media/image") {
			continue
		}
		base := baseName(name)
		base = strings.TrimPrefix(base, "image")
		if dot := strings.IndexByte(base, '.'); dot >= 0 {
			base = base[:dot]
		}
		if v := atoi(base); v > max {
			max = v
		}
	}
	return max
}

func baseName(p string) string {
	if i := strings.LastIndex(p, "/"); i >= 0 {
		return p[i+1:]
	}
	return p
}

// zipWrite writes text and binary parts into a .pptx ZIP archive.
func zipWrite(w io.Writer, textParts map[string]string, binParts map[string][]byte) (int64, error) {
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	// Deterministic order.
	names := make([]string, 0, len(textParts)+len(binParts))
	for name := range textParts {
		names = append(names, name)
	}
	for name := range binParts {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fw, err := zw.Create(name)
		if err != nil {
			return 0, err
		}
		if s, ok := textParts[name]; ok {
			if _, err := io.WriteString(fw, s); err != nil {
				return 0, err
			}
		} else if b, ok := binParts[name]; ok {
			if _, err := fw.Write(b); err != nil {
				return 0, err
			}
		}
	}
	if err := zw.Close(); err != nil {
		return 0, err
	}
	nn, err := w.Write(buf.Bytes())
	return int64(nn), err
}
